// Stub — original TanStack Start middleware is incompatible with this Next.js
// project. Auth runs client-side via @/lib/auth and server-side via Supabase
// Edge Functions. This file is auto-regenerated by the platform; the stub
// keeps it compiling under Next.js.
export const requireSupabaseAuth = null as unknown as never;
